services:
  - type: worker
    name: zyvilla-worker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run worker:start
    envVars:
      - key: FAL_KEY
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
    autoDeploy: true
